import * as React from "react"

const PleaseHelpPage = () => {
  console.log('Rendered Please Help Page')

  return (
    <article>
      <h1>Please Help</h1>
      <p>
        This is my minimum reproduction for my useStaticQuery bug
      </p>
      <p>
        To simplify things a lot, I've replaced my site's source data plugins with simple JSON sourcing and the bug still arises. (I was using <i>gatsby-source-wordpress</i> for the "activities" items and <i>gatsby-source-google-calendar</i> for the "calendar" items) 
      </p>
      <p>
        To reproduce the bug, open the console, and click "Activities". Then click one of the Activities. Then refresh the page. Finally, hover over any of the links on the page. You will see in the console that the page is rerendering on every link you hover over (You need to have refreshed the page to see this effect).
      </p>
      <p>
        This behaviour ONLY happens on one of the pages generated by "createPage". And it is something to do with the "useCalendar" hook (which is a container for a useStaticQuery hook).
      </p>
      <p>
        On my production site, when the page rerenders, the second time it renders, the useStaticQuery returns "undefined" causing the content to change. Which is not ideal obviously.
      </p>
      <p>
        What am I doing wrong?
      </p>
      <p>
        Any help you can offer would be greatly appreciated. Many thanks. Ben
      </p>
    </article>
  )
}

export default PleaseHelpPage
